packages:
  - packages/*
  - lib/*
catalog:
  dayjs: ^1.11.13
  globals: ^15.13.0
  typescript: ^5.6.2
  vite: ^6.0.3
  vite-plugin-babel: ^1.3.0
  "@babel/preset-typescript": ^7.26.0
  lucide-react: ^0.469.0

catalogs:
  react19:
    react: ^19.0.0
    react-dom: ^19.0.0
    "@types/react": ^19.0.1
    "@types/react-dom": ^19.0.1
    "babel-plugin-react-compiler": 19.0.0-beta-37ed2a7-20241206
  tailwindcss: 
    clsx: ^2.1.1
    daisyui: ^4.12.22
    tailwindcss: ^3.4.17
    tailwindcss-animate: ^1.0.7
    tailwind-merge: ^2.5.5
    autoprefixer: ^10.4.20
    postcss: ^8.4.49
    class-variance-authority: ^0.7.1


