packages:
  - packages/*
  - lib/*
catalog:
  "@eslint/js": ^9.17.0
  "@react-router/dev": ^7.0.2
  "@react-router/node": ^7.0.2
  "@react-router/serve": ^7.0.2
  "@types/node": ^20
  "@vitejs/plugin-react": ^4.3.4
  autoprefixer: ^10.4.20
  clsx: ^2.1.1
  cross-env: ^7.0.3
  daisyui: ^4.12.22
  dayjs: ^1.11.13
  eslint: ^9.17.0
  eslint-plugin-react-hooks: ^5.0.0
  eslint-plugin-react-refresh: ^0.4.16
  globals: ^15.13.0
  isbot: ^5.1.17
  msw: ^2.7.0
  postcss: ^8.4.49
  react: ^19.0.0
  react-dom: ^18.3.1
  react-router: ^7.0.2
  tailwind-merge: ^2.5.5
  tailwindcss: ^3.4.17
  tailwindcss-animate: ^1.0.7
  typescript: ~5.6.2
  typescript-eslint: ^8.18.1
  vite: ^6.0.3
  vite-tsconfig-paths: ^5.1.4
  wouter: ^3.3.5
